services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "4003:3000"
    restart: always

    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./app/api/data:$HOME/docker/docker-compose/data/
    
  view:
    build:
      context: ./view/
      dockerfile: Dockerfile
    ports:
      - "4002:80"

    environment:
      - NODE_ENV=production
      