services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - PORT=3000
    
  view:
    build:
      context: ./view/
      dockerfile: Dockerfile
    ports:
      - "8080:80"

    environment:
      - NODE_ENV=production
      